// 类型定义已由 Prisma 自动生成，此文件保留用于自定义类型
// 使用方式：import type { User, Team, Registration } from "@prisma/client"

export type {
  User,
  Role,
  StudentPosition,
  Permission,
  Session,
  RegistrationStatus,
  StaffApplicationStatus,
  AnnouncementType,
  MaterialStatus,
  GameStation,
  ClueCardTier,
  Registration,
  Team,
  TeamMember,
  GameStationConfig,
  RotationSchedule,
  Score,
  StaffRole,
  StaffAssignment,
  ScheduleItem,
  Announcement,
  Material,
  TreasureCard,
  ClueCard,
  Feedback,
  Album,
  ActivityLog,
  ImportBatch,
  ImportLog,
  AdminPermission,
} from "@prisma/client"
